name: Test and CDK Synth
permissions:
  contents: read

on:
  push:
    branches: [main, feat/hakanson/search-api]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test_and_synth:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: |
          npm run lint
          npx vitest test/cedar-authzen.test.ts
          export POLICY_STORE_ID=cedar/todo-app/
          export ENTITIES_TABLE_NAME=cedar/todo-app/cedarentities.json
          npx vitest test/server.test.ts

      - name: CDK Synth AuthZENPolicyStoreStack
        run: |
          cd cdk
          npx cdk synth AuthZENPolicyStoreStack
